name: hello

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo Hello, world!
    - run: |
        echo Add other actions to build,
        echo test, and deploy your project.
